python extract_msssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param 5 
python extract_msssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param 1 
python extract_msssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param 0.5 
python extract_msssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param -5 
python extract_msssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param -1 
python extract_msssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param -0.5 
python extract_msssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method none --patch_size 31 --type local --nonlinear_param -0.5 
python extract_ssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param 5 
python extract_ssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param 1 
python extract_ssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param 0.5 
python extract_ssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param -5 
python extract_ssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param -1 
python extract_ssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method texp --patch_size 31 --type local --nonlinear_param -0.5 
python extract_ssim.py --framenos_list /home/zs5397/code/hdr_fr_code/spring2022_yuv_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRAQ_correct/ --nonlinear_method none --patch_size 31 --type local --nonlinear_param -0.5 
python extract_msssim.py --framenos_list /mnt/31393986-51f4-4175-8683-85582af93b23/videos/HDR_2021_fall_yuv_upscaled/fall2021_yuv_rw_info.csv --output_pth /media/zaixi/zaixi_nas/HDRproject/feats/fr_evaluate_HDRLIVE_correct/ --nonlinear_method none 